import Head from 'next/head'
import { Inter } from '@next/font/google'
import ComponentsGrid from '../src/components/ComponentsGrid';
import ButtonAppBar from '../src/components/ButtonAppBar';
import MySorobanReactProvider from '../src/MySorobanReactProvider';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Multichain Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MySorobanReactProvider>
        <ButtonAppBar/>
        <ComponentsGrid/>
      </MySorobanReactProvider>
    </>
  )
}
